name: ChatGPT Auto-Response

on:
  issues:
    types: [opened]

jobs:
  chatgpt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Call OpenAI API
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          RESPONSE=$(curl -X POST "https://api.openai.com/v1/chat/completions" \
          -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "gpt-4",
            "messages": [
              {"role": "system", "content": "You are an AI assistant responding to GitHub Issues."},
              {"role": "user", "content": "'"$ISSUE_BODY"'"}
            ]
          }')

          COMMENT_BODY=$(echo $RESPONSE | jq -r '.choices[0].message.content')

          curl -X POST "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{\"body\": \"$COMMENT_BODY\"}"
